#include <stdio.h>

const char *dict[] = {
"a","ah! ha! oh! ooh! aw! (emotion word)",
"ala","no, not, none, negation, zero, un-",
"ale","they, all, everything, anything, complete, whole",
"akesi","non-cute earth animal, reptile, amphibian, etc.",
"anpa","low, bottom, lower, down, under, below, floor",
"ante","different, other, changed, otherwise",
"awen","keep, stay, wait, reside",
"e","(introduces a direct object)",
"en","and",
"ijo","thing, something, stuff, anything",
"ike","bad, evil",
"iki","he, she, it, him, her, his, its",
"ilo","tool, device, machine",
"insa","between, middle, centre, inside, stomach, torso",
"jaki","disgusting, dirty, pollution",
"jan","person, people, human, being, somebody, anybody, one",
"jelo","yellow",
"jo e","to have, contain, possess",
"kala","fish, sea creature",
"kalama","sound, noise, voice",
"kama","to come, become, appear, arrive, happen, succeed, manage, then",
"kan","to be/do/go with, accompany, among",
"kapa","hill, mountain, bump, button",
"kapesi","brown, grey",
"kasi","plant, tree, wood",
"ken","can, is able to, is allowed to, may, probable, is possible, maybe, power",
"kepeken","use, with use of",
"kili","fruit, vegetable",
"kin","also, too, even, indeed",
"ko","paste, substance, powder",
"kon","air, wind, smell, atmosphere, mood, spirit, soul",
"kule","colour",
"kute e","listen, hear",
"la","(between adverb of context and subject)",
"lape","rest, sleep",
"laso","blue, green",
"lawa","head, main, lead, mind, brain, opinion, thought",
"leko","block, square object, cube, stairs",
"len","clothing, cloth",
"lete","cold, uncooked",
"li","(separates any subject except mi and sina from its verb)",
"lili","small, little, a bit, short, few, less, young",
"linja","line, family, rope, thread, string, cord, chain",
"lipu","paper, card, ticket, something flat",
"lape","to sleep, rest",
"loje","red",
"lon","to be (located) in/at/on, be there/present/real/true, exist",
"luka","hand, arm, five, overly complicated number or thing",
"lukin e","to see, perceive, look at, watch, watch out, pay attention, visit",
"lupa","hole, loop, window, door, orifice",
"ma","land, earth, country, outdoor area",
"mama","father, mother, parent",
"mani","money, material wealth, treasure, currency, dollar",
"meli","woman, female, girl, wife",
"mi","I, me, my",
"mije","man, male, guy, husband",
"moku","food, meal",
"moku e","to eat, drink, swallow",
"moli","die, death, kill",
"monsi","back, rear end, behind",
"mun","moon",
"musi","to play, have fun",
"mute","many, several, very, much, quantity, amount, a lot, abundant, numerous, more",
"nanpa","number, -th",
"nasa","crazy, silly, foolish, drunk, strange, stupid, strange, weird",
"nasin","way, manner, custom, road, path",
"ni","this, that",
"nimi","name",
"noka","leg, foot",
"o","O! (vocative or imperative)",
"oko","eye",
"olin e","to love romantically",
"open e","to open, turn on",
"pakala e","to screw up, botch, ruin, break, hurt, injure, damage, accident",
"pali","life, activity, work, deed, doing, project",
"pali e","to do, make, act, work, function, be alive",
"palisa","rod, stick, long or pointy thing",
"pana e","to give, put, send, place, release, emit",
"pi","of",
"pilin","feelings, heart, emotion",
"pimeja","black, dark, darkness, shadows",
"pini","done, past, ready, end, tip, ago",
"pini e","finish, close, end, turn off",
"pipi","bug, insect, spider",
"po","four",
"poka","side, hip, neighbouring, next to",
"poki","container, box, bowl, cup, glass",
"pona","good, nice, positive, correct, OK, cool, thanks!, simple, sound, right",
"sama","same, similar, seem, equal, like, as",
"seli","fire, hot, warm, cooked",
"selo","outside, surface, skin, shell, bark, shape",
"seme","what, which, wh-",
"sewi","high, up, above, top, superior, over, on, elevated, noble, religious, supernatural",
"sijelo","body, physical, state, health",
"sike","circle, round, sphere, ball, cycle, year, group, community, company",
"sin","new, fresh, another, more",
"sina","you",
"sinpin","front, chest, wall",
"sitelen","picture, image, draw, idea",
"sona","knowledge, science, intelligence, understanding, wisdom, know how to",
"soweli","land mammal, animal",
"suli","big, tall, long, important",
"suno","sun, light",
"supa","horizontal surface, table, chair, etc.",
"suwi","sweet, candy, cute",
"tan","from, by, because of, origin, cause",
"taso","but, only",
"tawa","to go to, move, walk, travel, to, in order to, towards, for, until",
"telo","water, liquid, juice, sauce",
"tenpo","time, period, if, when",
"toki","language, talking, speech, communication",
"tomo","house, room, place, building, constructed space",
"tu","two",
"tuli","three",
"unpa e","have sex with",
"uta","mouth",
"utala","fight, hit, strike, war, battle, compete",
"walo","white",
"wan","one, a, unit, element, particle, part, piece",
"waso","bird, flying animal",
"wawa","strong, energy, hard, fierce, intense, sure",
"weka","away",
"wile e","to want, need, wish, have to, must, will",
NULL
};
