#include <stdio.h>

const char *dict[] = {
"holy macaroni","(emotion word)",
"aloha snackbar","no, not, none, negation, zero, un-",
"42","all, everything, anything, complete, whole",
"clog","animal, disgustuing, loner (derogatory)",
"connellweird.mp4","thing, something, stuff, anything",
"swanson","redneck, libertarian, anti-government",
"trump","disgusting, dirty, evil",
"jello","god, idol, worship, etc.",
"spoopy","spooky, scary, fear",
"nithin","gay, same, homo",
"ethan","indifference, the act of not caring",
"salty","angry, anger, mad, unduly angry",
"good mythical morning","(traditional greeting)",
"let's talk about that","(traditional response to 'good mythical morning')",
"gas mask","joke, laughter, funny",
"with moana","with, group, companionship, friend",
"enemy missile inbound","alarm, friendly warning, threat, danger",
"down the road","response, answer, (traditional response to a difficult question)",
"the kkk","kaya, kmei, katelyn",
"kmei","killer, murderer, death, null, destruction",
"CNN10","failure, worthless, untouchable, to be avoided",
"you will die alone, having never been loved","(derogatory, general insult)",
"garmin watch","smart, intelligence, watch, time",
"stapled","attacked, abused, killed",
"meme-stealing hack","stealer, cheating, cheat",
"conservative","annoying, resistant,argumentative",
NULL
};
